project_id = "pukezienbcenozlqmunf"

[functions.setup-demo-users]
verify_jwt = false

[functions.test-autocount-connection]
verify_jwt = false

[functions.test-inventory-endpoints]
verify_jwt = false

[functions.update-autocount-item]
verify_jwt = true

[functions.sync-stock-adjustment]
verify_jwt = true

[functions.sync-po-create]
verify_jwt = true

[functions.sync-po-cancel]
verify_jwt = true

[functions.sync-suppliers-preview]
verify_jwt = false

[functions.sync-suppliers-execute]
verify_jwt = false

[functions.sync-inventory-preview]
verify_jwt = false

[functions.sync-inventory-execute]
verify_jwt = false

[functions.create-autocount-item]
verify_jwt = false