project_id = "pukezienbcenozlqmunf"

[functions.pull-po-from-autocount]
verify_jwt = false

[functions.pull-po-execute]
verify_jwt = false

[functions.setup-demo-users]
verify_jwt = false

[functions.test-autocount-connection]
verify_jwt = false

[functions.test-inventory-endpoints]
verify_jwt = false

[functions.update-autocount-item]
verify_jwt = true

[functions.sync-stock-adjustment]
verify_jwt = true

[functions.sync-po-create]
verify_jwt = true

[functions.sync-po-cancel]
verify_jwt = true

[functions.sync-suppliers-preview]
verify_jwt = false

[functions.sync-suppliers-execute]
verify_jwt = false

[functions.create-autocount-supplier]
verify_jwt = false

[functions.sync-inventory-preview]
verify_jwt = false

[functions.sync-inventory-execute]
verify_jwt = false

[functions.create-autocount-item]
verify_jwt = false

[functions.sync-grn-to-autocount]
verify_jwt = true

[functions.sync-goods-return]
verify_jwt = true

[functions.sync-cash-purchase]
verify_jwt = true

[functions.sync-assembly-complete]
verify_jwt = true

[functions.delete-autocount-item]
verify_jwt = false

[functions.push-po-to-autocount]
verify_jwt = true

[functions.sales-api-proxy]
verify_jwt = true

[functions.retry-failed-sync]
verify_jwt = true